export const SET_STATE = 'SET_STATE';

//Organization Repos
export const SET_ORGANIZATION_REPOS_DATA = 'SET_ORGANIZATION_REPOS_DATA';
export const FETCH_ORGANIZATION_REPOS_DATA_FAIL = 'FETCH_ORGANIZATION_REPOS_DATA_FAIL';
export const GET_ORGANIZATION_REPOS_DATA = 'GET_ORGANIZATION_REPOS_DATA';
export const GET_ORGANIZATION_REPOS_DATA_START = 'GET_ORGANIZATION_REPOS_DATA_START';

//Hanlde restar
export const RESTART_ORGANIZATION_DATA = 'RESTART_ORGANIZATION_DATA';
export const RESTART_REPO_COMMITS_DATA = 'RESTART_REPO_COMMITS_DATA'

//Repo Commits
export const SET_REPO_COMMITS_DATA = 'SET_REPO_COMMITS_DATA';
export const FETCH_REPO_COMMITS_DATA_FAIL = 'FETCH_REPO_COMMITS_DATA_FAIL';
export const GET_REPO_COMMITS_DATA = 'GET_REPO_COMMITS_DATA';
export const GET_REPO_COMMITS_DATA_START = 'GET_REPO_COMMITS_DATA_START';

//Form
export const HANDLE_ORGANIZATION_NAME_CHANGE = 'HANDLE_ORGANIZATION_NAME_CHANGE';
export const HANDLE_REPO_NAME_CHANGE = 'HANDLE_REPO_NAME_CHANGE';
export const RESTART_FORM = 'RESTART_FORM';
export const RESTART_CLICK = 'RESTART_CLICK';
export const SEARCH_CLICK = 'SEARCH_CLICK';
